import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import One from "./Components/One";
import Navbar from "./Components/Navbar";
import About from "./Components/About";
import { Fade } from "react-reveal";
import Projects from "./Components/Projects";
import data from "./Components/data";
import Contact from "./Components/Contact";
export default function Home() {
  const { products } = data;
  return (
    <div className="th">
      <Head>
        <title>My Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      <One />
      <Fade>
        <About />
      </Fade>
      <Fade>
        <Projects products={products} />
      </Fade>
      <Fade>
        <Contact />
      </Fade>

      {/* <div className="font-sans ">Hello</div> */}
    </div>
  );
}
